### ISSUE TITLE
Vertical alignment issue for labels using TeX and subscripts

### ISSUE THREAD

**Issue by ChronoJon** [kakearney/legendflex-pkg#5]
When there are TeX subscripts in the label text, the legend symbol is too low, making it look weird (tested in R2015a and R2014a, so no HG2 issue):
```matlab
x = 1:100
figure
plot(x,x)
legend({'f_{oobar}'})
title('legend')
```
![legend](https://cloud.githubusercontent.com/assets/12965550/8252423/41cb750e-1686-11e5-8da3-8c72fa2581b5.png)

```matlab
figure
plot(x,x)
legendflex({'f_{oobar}'})
title('legendflex')
```
![legendflex](https://cloud.githubusercontent.com/assets/12965550/8252429/4f670a66-1686-11e5-8e30-dfd7bb926652.png)

**Comment by kakearney** [comment]
Unfortunately, the Latex (and occassionally, plain Tex) renderers don't always play nicely with legendflex.  It's something that bugs me in my own work too, but I've never been able to come up with a good workaround that would position things properly.  The legendflex function repositions everything using the 'Extent' property of all the text in the original legend.  However, the extent property of tex-rendered text doesn't always match up with the actual space taken up by the text... not quite sure why this is, and therefore I don't have a reliable way to calculate what that real space is. 

Here's an example using plain text objects:

```matlab
p = {'horiz', 'center', 'fontsize', 16};

axes('xlim', [0 1], 'ylim', [0 1]);

ht(1) = text(0.5, 0.8, 'f_{oobar}', 'interpreter', 'none', p{:});
ht(2) = text(0.5, 0.5, 'f_{oobar}', 'interpreter', 'tex', p{:});
ht(3) = text(0.5, 0.2, '$f_{oobar}$', 'interpreter', 'latex', p{:});

ex = get(ht, 'extent');
cellfun(@(x) rectangle('position', x, 'edgecolor', 'r'), ex);
line([0 1], [0.2 0.5 0.8]'*ones(1,2));
```
![legendflex_tex](https://cloud.githubusercontent.com/assets/5015092/8258775/8f53e42e-166c-11e5-9bc0-e371e206f1c0.png)

As you can see, with the Tex renderer (the default in legend and therefore also in legendflex), the Extent doesn't wrap tightly to the text but rather leaves some space at the bottom.  In the legendflex legend, this leads to the text being placed a bit too high relative to the corresponding symbol.  

I've tried playing around with automated adjustments (for example, shift text down a pixel or two if subscripts are found), but I haven't found any fixes that work robustly for all possible situations.  Because of this, you really need to play around with properties in order to get a legendflex legend that uses latex or tex and looks decent.  Sometimes generating the legend first specifying 'none' for the Interpreter, then setting the latex/tex rendering afterwards will help a bit.  Other times I generate the legend using a larger font size, then shrink the text back down after it's been positioned (this particularly helps when too-high text is running into the legend box).  More often I just resort to manual tweaks specific to a given example.  In your case, I added a little extra padding to the right, and manually shifted the text down:

```matlab
x = 1:100
plot(x,x)
[hl, ho] = legendflex({'f_{oobar}'}, 'padding', [2 1 3])
drawnow;
ho(1).Position = ho(1).Position - [0 4 0];
```
![legendflex_tex2](https://cloud.githubusercontent.com/assets/5015092/8259225/d0e2628c-166f-11e5-981c-0dc4ce75c6d7.png)

**Comment by ChronoJon** [comment]
Wow... thank you for the comprehensive answer. At least, I will be able to fix it this way,  to make it look fine.
And also thank you for the amazing function in the first place. I will close the issue then.

**Comment by sorenenemark** [comment]
I might have come up with a solution that gives ok results:
```matlab
figure
hold on
plot([0 1],[1 1]);
plot([0 1],[2 0]);
plot([0 1],[0 .5]);

[legend_h,object_h] = legendflex({'$f_{1}$','$\omega^{\pi}$','$\sum x$'},...
    'anchor',{'ne' 'ne'},'xscale',.6,'padding',[2 1 3],'interpreter','latex','fontsize',16);
nrow = 3; %number of rows (hard coded)
textobj = findall(object_h,'type','text'); %legend labels
yheight = legend_h.YLim(2); %height of legend axis
ylow    = textobj(nrow).Extent(2); %lowest label text position
yhigh   = sum(textobj(1).Extent([2 4])); %highest label text position
ydiff   = yheight/2 - .5*(ylow + yhigh); %correction
for kk = 1:length(textobj) %correct
    textobj(kk).Position(2) = textobj(kk).Position(2) + ydiff;
end
```
This is without correction
![without](https://cloud.githubusercontent.com/assets/1997939/9435031/69a020b0-4a44-11e5-9eac-e02f7da0aae3.png)

This is with correction
![with](https://cloud.githubusercontent.com/assets/1997939/9435038/77f4da70-4a44-11e5-84fa-63fdb867954a.png)

I don't know how robust the solution is though...

**Comment by TobiasDK** [comment]
This will work for R2014a and before. Same trick as @sorenenemark:

```
textobj = findall(hnew.obj,'type','text'); %legend labels
yheight = get(hnew.leg,'YLim');yheight=yheight(2); %height of legend axis
ylow    = get(textobj(end),'Extent');ylow=ylow(2); %lowest label text position
yhigh   = get(textobj(1),'Extent');yhigh=sum(yhigh([2 4])); %highest label text position
ydiff   = yheight/2 - .5*(ylow + yhigh); %correction
for kk = 1:length(textobj) %correct
    post = get(textobj(kk),'Position');
    set(textobj(kk),'Position',[post(1) post(2)+ydiff post(3)]);
end
```

**Comment by kakearney** [comment]
I had added a similar fix based on @sorenenemark's suggestions, but then realized that it causes problems when a title is included, along with a few other edge cases.  For now, I've removed the adjustments from the code until I can test a more robust solution.
